import json
import boto3
import uuid

s3 = boto3.client("s3")

WEBAPP_PREFIX = "webapp/"          # images used by the webapp (trigger ON)
IMG_PREFIX    = "img/"             # test images stored here (trigger OFF)
BW_PREFIX     = "bw-"              # prefix for BW files generated by the Lambda converter


def cors_headers():
    return {
        "Content-Type": "application/json",
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Headers": "Authorization,Content-Type",
        "Access-Control-Allow-Methods": "GET,OPTIONS",
    }


def lambda_handler(event, context):
    bucket_name = event["pathParameters"]["bucket"]
    file_name = event["queryStringParameters"]["file"]
    mode = event["queryStringParameters"]["mode"]

    # Validate extension
    if "." not in file_name:
        return {
            "statusCode": 400,
            "headers": cors_headers(),
            "body": json.dumps(
                {"error": "File name must have an extension (.jpg, .jpeg, .png)"}
            ),
        }

    ext = file_name.rsplit(".", 1)[-1].lower()

    if ext in ("jpg", "jpeg"):
        content_type = "image/jpeg"
    elif ext == "png":
        content_type = "image/png"
    else:
        return {
            "statusCode": 400,
            "headers": cors_headers(),
            "body": json.dumps({"error": "Only JPG, JPEG and PNG are allowed."}),
        }
    
    if mode == "upload":

        object_key = f"{WEBAPP_PREFIX}{file_name}"   # e.g., webapp/dog.jpg

        URL = s3.generate_presigned_post(Bucket=bucket_name, Key=object_key, Fields=None, Conditions=None, ExpiresIn=6000)

        body = {"URL": URL}
    elif mode == "download":
        object_key = f"{WEBAPP_PREFIX}{BW_PREFIX}{file_name}"  # e.g., webapp/bw-dog.jpg

        URL = s3.generate_presigned_url("get_object", Params={"Bucket":bucket_name, "Key": object_key}, ExpiresIn=600)

        body = {"URL": URL}
    elif mode == "copy":
        source_key = f"{IMG_PREFIX}{file_name}" # it becomes "img/large/earth.png"

        # generate UUID for the new file name
        unique_id = uuid.uuid4().hex
        new_filename = f"{unique_id}.{ext}"

        # destination under webapp/
        dest_key = f"{WEBAPP_PREFIX}{new_filename}"

        copy_source = {
            "Bucket": bucket_name,
            "Key": source_key,
        }

        s3.copy_object(
            Bucket=bucket_name,
            Key=dest_key,
            CopySource=copy_source,
        )

        # this is what you really need afterward: new_filename
        body = {
            "new_file": new_filename,
            "s3_path": f"s3://{bucket_name}/{dest_key}",
        }

    else:
        return {
            "statusCode": 400,
            "headers": cors_headers(),
            "body": json.dumps({"error": "Invalid mode"}),
        }

    return {
        "statusCode": 200,
        "headers": cors_headers(),
        "body": json.dumps(body),
    }